// Drives the C4 mock through every state and serializes each to states/<id>.json (+ reference png)
const open = require('./cdp'), fs = require('fs');
const URL = 'file:///C:/Users/tieun/ray-word-addin/ray-word-addin-interactive-c4.html';
fs.mkdirSync(__dirname + '/states', { recursive: true });
const only = process.argv[2] ? process.argv[2].split(',') : null;
const meta = [];
const HELP = `
window.$c=s=>{const e=document.querySelector(s);if(!e)throw new Error('missing '+s);e.click();};
window.$type=(s,t)=>{const e=document.querySelector(s);if(!e)throw new Error('missing '+s);e.focus();e.innerText=t;e.dispatchEvent(new Event('input',{bubbles:true}));};
window.$see=s=>{const e=document.querySelector(s);if(!e)throw new Error('missing '+s);e.scrollIntoView({block:'center'});};
window.$top=()=>{const p=document.querySelector('.pbody');if(p)p.scrollTop=0;};
window.$sel=(id,v)=>{const e=document.getElementById(id);e.value=v;e.dispatchEvent(new Event('change',{bubbles:true}));};
document.head.insertAdjacentHTML('beforeend','<style>*,*::before,*::after{animation:none!important;transition:none!important}</style>');1`;

(async () => {
  const b = await open(URL);
  await b.send('Emulation.setFocusEmulationEnabled', { enabled: true });
  const SER = fs.readFileSync(__dirname + '/ser.js', 'utf8');
  const fresh = async () => { await b.go(URL); await b.ev(SER + ';' + HELP); };
  const until = async (expr, ms = 8000) => { const t = Date.now(); while (Date.now() - t < ms) { if (await b.ev(expr)) return; await b.sleep(100); } throw new Error('timeout ' + expr); };
  const run = async js => { await b.ev(js + ';1'); await b.sleep(250); };
  const snap = async (id, title, note, group) => {
    meta.push({ id, title, note, group });
    if (only && !only.includes(id)) return;
    await b.sleep(150);
    const t = await b.ev(`(()=>{const to=document.querySelector('#toast');return window.__ser(document.querySelector('#win'),to.classList.contains('on')?[to]:[])})()`);
    t.name = id + ' · ' + title;
    fs.writeFileSync(`${__dirname}/states/${id}.json`, JSON.stringify(t));
    await b.shot(`${__dirname}/states/${id}.png`);
    console.log(id, JSON.stringify(t).length);
  };
  const boot = async () => { await fresh(); await run(`$c('[data-do=picktender][data-i="0"]')`); await run(`$c('[data-do=pickfolder][data-f="Default"]')`); await until(`ui.view==='list'&&!!ui.scan`); await b.sleep(300); };
  const finish = async () => { await run(`$c('.demoscan')`); await b.ev(`document.querySelector('#toast').classList.remove('on');1`); };
  const CORR = 'Our Chain of Responsibility controls follow the NHVR Safety Management System: telematics fatigue and speed monitoring, load-restraint checks before every dispatch, and quarterly CoR audits reported to the board.';

  /* ---------- happy flow ---------- */
  await fresh();
  await snap('H01', 'Choose a tender', 'Ray opens on an unlinked document and asks which Tenderfy tender it belongs to. Nothing else in the pane works until a tender is picked.', 'happy');
  await run(`$c('[data-do=picktender][data-i="0"]')`);
  await snap('H02', 'Choose a folder', 'Pick the tender folder the document is filed under, or create a new one. Back returns to the tender list.', 'happy');
  await b.ev(`$c('[data-do=pickfolder][data-f="Default"]');1`); await b.sleep(700);
  await snap('H03', 'Reading the document', 'Ray reads the file section by section in place. Nothing is copied out of Word; the user can keep working.', 'happy');
  await until(`ui.view==='list'&&!!ui.scan`); await b.sleep(250); await run(`$top()`);
  await snap('H04', 'Ray scanning the Response Library', 'Every open question shows "Ray is analysing". The scan card sits above Apply to document. Rows stay clickable, so answering can start right away.', 'happy');
  await run(`$c('.demoscan')`); await run(`$top()`);
  await snap('H05', 'Analysis finished', 'Library matches go straight into the document (Response Library tag, Inserted). Questions with no match get a Ray draft (AI generated tag, Put in document). The toast counts each.', 'happy');
  await run(`$see('.wr[data-q="3.7"]')`);
  await snap('H06', 'Open questions and AI drafts', 'AI generated drafts wait for a click to go in; questions owned by teammates stay open with "Click to answer".', 'happy');
  await run(`$c('.wr[data-q="4.1"]')`);
  await snap('H07', 'Question card · empty', 'The card: section and source tag, full question, the editor box with Write manually / Answer with Ray tabs, and Put in document & next.', 'happy');
  await run(`$type('#edbody','We expect to engage four local employees on this contract: two Bundaberg depot staff for receiving and dispatch, one local driver, and a part-time administrator.')`);
  await snap('H08', 'Answer written', 'Typing enables Put in document & next (Ctrl+Enter). Previous / Next Question and Not a question sit underneath.', 'happy');
  await run(`$c('#primbtn')`); await b.sleep(250);
  await snap('H09', 'Put in document & next', 'The answer goes in as a tracked change and the card moves to the next question still to answer or check.', 'happy');
  await run(`$c('[data-do=list]')`); await run(`$see('.wr[data-q="4.1"]')`);
  await snap('H10', 'Back in the list · Inserted', 'The row now shows the answer with an Inserted pill; the Apply count goes up.', 'happy');
  await run(`$c('.wr[data-q="3.2"] .t b')`);
  await snap('H11', 'Library answer · review', 'A Response Library answer opens with the text in the editor and the source tag beside the section name.', 'happy');
  await run(`$type('#edbody','We hold buffer stock of the full HDPE range at our Bundaberg depot (opened 2025), with weekly replenishment from Brisbane. Standard orders are delivered within 2 business days; urgent orders confirmed by 10am are delivered the same day.')`);
  await snap('H12', 'Edited → Put in document', 'Editing an inserted answer and pressing Put in document rewrites it as a tracked change.', 'happy');
  await run(`$c('#primbtn')`); await b.sleep(250); await run(`$c('[data-do=list]')`);
  await run(`$see('.wr[data-q="1.8"]')`); await run(`$type('.wr[data-q="1.8"] .qa .in','07 4152 0001')`); await run(`document.activeElement.blur()`);
  await run(`$see('.wr[data-q="1.12"]')`); await run(`$type('.wr[data-q="1.12"] .qa .in','accounts@eiwa.com.au')`); await run(`document.activeElement.blur()`);
  await run(`$see('.wr[data-q="1.8"]')`);
  await snap('H13', 'Drafts ready to apply', 'Answers left mid-typing are kept as drafts with Put in document. Apply to document puts every draft in at once.', 'happy');
  await run(`$c('.cta [data-do=insall]')`);
  await snap('H14', 'Apply to document', "All drafts land as tracked changes in one go; the count updates. Accept or reject them from Word's Review tab.", 'happy');

  /* ---------- edge cases ---------- */
  await boot();
  await run(`$see('.wr[data-q="8.3"]')`); await run(`$type('.wr[data-q="8.3"] .qa .in','No conflicts of interest to declare.')`);
  await snap('E01', 'Answering while Ray is still analysing', 'The inline field works during the scan. A quick answer can go in before Ray finishes; Ray skips anything already answered.', 'edge');
  await run(`$c('.wr[data-q="2.3"]')`);
  await snap('E02', 'Opening a question Ray is still analysing', 'The card shows Ray searching the Response Library for this question.', 'edge');
  await finish(); await run(`$c('[data-do=list]')`);
  await run(`$see('.wr[data-q="5.5"]')`);
  await snap('E03', 'No library match → AI generated', 'With no library match Ray drafts the answer during the scan and leaves it for the user to check and put in.', 'edge');
  await run(`$see('.wr[data-q="1.8"]')`); await run(`$type('.wr[data-q="1.8"] .qa .in','07 4152 0001')`);
  await snap('E04', 'Quick inline answer', 'A short answer typed into the row. Enter puts it in and jumps to the next open question; Shift+Enter opens the full editor.', 'edge');
  await run(`$type('.wr[data-q="1.8"] .qa .in','07 4152 0001 (main) and 07 4152 0002 (after hours), both monitored on weekdays from 7am to 5pm AEST.')`);
  await snap('E05', 'Inline answer getting long', 'Past ~85 characters a note suggests the full editor (Shift+Enter).', 'edge');
  await run(`document.activeElement.blur()`);
  await snap('E06', 'Left mid-typing → draft kept', 'Clicking away keeps the text as a draft with Put in document instead of losing it.', 'edge');
  await run(`$see('.wr[data-q="5.4"]')`);
  await snap('E07', 'Assigned to someone else', 'Rows assigned to a teammate show their avatar, name and due day. You can still click to answer.', 'edge');
  await run(`$top()`); await run(`$see('.wr[data-q="3.1"]')`);
  await snap('E08', 'Edited by a teammate in Word', 'If Mia changes an answer directly in the document, the row flags it.', 'edge');
  await run(`$c('.wr[data-q="3.1"] .t b')`);
  await snap('E09', 'Teammate edit · card', 'The note at the bottom of the editor says Mia changed it; replacing her text asks first.', 'edge');
  await run(`$c('[data-do=list]')`); await run(`$see('.wr[data-q="3.2"] .more')`); await run(`$c('.wr[data-q="3.2"] .more')`);
  await snap('E10', 'Long answer · Show more', 'Answers clamp to two lines; Show more expands in place.', 'edge');
  await run(`$c('.wr[data-q="6.1"]')`);
  await snap('E11', 'Card for an open question', 'Empty editor, Put in document & next disabled until there is text.', 'edge');
  await run(`$c('.hasg')`);
  await snap('E12', 'Assign from the card header', 'Assign User in the header opens the people menu to assign or reassign inline.', 'edge');
  await run(`document.querySelector('.cmenu')?.remove()`);
  await run(`$c('.ctabs .ptab[data-k=ray]')`); await run(`$c('.rffile')`);
  await snap('E13', 'Answer with Ray · draft from a file', 'The paperclip opens an in-pane picker: a Tenderfy file name or an upload.', 'edge');
  await run(`$c('.gdlg [data-do=genfile]')`); await run(`$c('.qempty .starter')`); await b.sleep(100);
  await snap('E14', 'Answer with Ray · drafting', 'Ray drafts this question in a per-question conversation.', 'edge');
  await b.sleep(1500);
  await snap('E15', 'Answer with Ray · reply', 'Each reply shows its source, Use this answer, copy, retry and follow-up suggestions.', 'edge');
  await run(`$c('.qthread [data-do=quse]')`);
  await snap('E23', 'Use this answer → editor', 'Use this answer drops the reply into the editor and switches back to Write manually.', 'edge');
  await run(`$c('.ctabrow [data-do=fullscreen]')`); await b.sleep(400);
  await snap('E16', 'Full screen', 'The editor box takes the pane; only the tabs and Put in document & next stay.', 'edge');
  await run(`$c('.ctabs .ptab[data-k=ray]')`); await b.sleep(200);
  await snap('E24', 'Full screen · Ray', 'Full screen works for the Ray conversation too.', 'edge');
  await run(`$c('.ctabs .ptab[data-k=write]')`); await run(`$c('.ctabrow [data-do=fullscreen]')`); await b.sleep(400);
  await run(`$c('.naq')`); await run(`$c('[data-do=list]')`);
  await run(`$c('[data-do=sec][data-s="X"]')`); await run(`$see('[data-do=sec][data-s="X"]')`);
  await snap('E17', 'Not a Question', 'Dismissed items leave the queue and the count, and collect in a Not a Question section with Restore.', 'edge');
  await run(`$top()`); await run(`$c('[data-do=filter][data-f=mine]')`);
  await snap('E18', 'Assigned to me', 'The Assigned switch narrows the list to questions assigned to you.', 'edge');
  await run(`$c('[data-do=filter][data-f=all]')`); await run(`$sel('whosel','MW')`);
  await snap('E19', 'Filter by person', "In All, the person filter shows one teammate's questions across sections.", 'edge');
  await run(`$sel('whosel','')`); await run(`$sel('stfsel','open')`); await run(`$top()`);
  await snap('E20', 'Status filter · Open', 'Open shows everything not yet in the document: unanswered questions and drafts.', 'edge');
  await run(`$sel('stfsel','')`); await run(`$c('.bell')`);
  await snap('E21', 'Notifications', 'The bell lists assignments and teammate answers; clicking one opens that question.', 'edge');
  await run(`document.querySelector('.cmenu')?.remove()`); await run(`$c('.wr[data-q="1.1"]')`);
  await snap('E22', 'First in the queue', 'Previous Question is disabled on the first item. Fields in the Tenderer Details Form use the same card.', 'edge');
  await run(`$c('[data-do=list]')`); await run(`$c('.wr[data-q="7.4"]')`);
  await snap('E26', 'AI generated draft · card', 'An AI generated draft opens with the text in the editor and the AI generated tag; put it in once checked.', 'edge');
  await run(`$c('[data-do=list]')`); await run(`$c('[data-do=tab][data-tab=ask]')`);
  await run(`$type('#cin','Draft 3.2');document.querySelector('#cin').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`); await b.sleep(1700);
  await run(`$type('#cin','make it shorter');document.querySelector('#cin').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`); await b.sleep(1700);
  await run(`const p=document.querySelector('.pbody');p.scrollTop=p.scrollHeight`);
  await snap('E25', 'Ask Ray · conversation', 'Ask Ray is a full conversation: follow-ups rework the last answer, Use for puts it in a question, history and context chips sit around it.', 'edge');

  fs.writeFileSync(__dirname + '/states/meta.json', JSON.stringify(meta, null, 1));
  b.close();
})().catch(e => { console.error(e); process.exit(1); });
