// Drives the C4 mock through every state and serializes each to states/<id>.json (+ reference png)
const open = require('./cdp'), fs = require('fs');
const URL = 'file:///C:/Users/tieun/ray-word-addin/ray-word-addin-interactive-c4.html';
fs.mkdirSync(__dirname + '/states', { recursive: true });
const only = process.argv[2] ? process.argv[2].split(',') : null;
const meta = [];
const HELP = `
window.$c=s=>{const e=document.querySelector(s);if(!e)throw new Error('missing '+s);e.click();};
window.$type=(s,t)=>{const e=document.querySelector(s);if(!e)throw new Error('missing '+s);e.focus();e.innerText=t;e.dispatchEvent(new Event('input',{bubbles:true}));};
window.$see=s=>{const e=document.querySelector(s);if(!e)throw new Error('missing '+s);e.scrollIntoView({block:'center'});};
window.$top=()=>{const p=document.querySelector('.pbody');if(p)p.scrollTop=0;};
window.$sel=(id,v)=>{const e=document.getElementById(id);e.value=v;e.dispatchEvent(new Event('change',{bubbles:true}));};
document.head.insertAdjacentHTML('beforeend','<style>*,*::before,*::after{animation:none!important;transition:none!important}</style>');1`;

(async () => {
  const b = await open(URL);
  await b.send('Emulation.setFocusEmulationEnabled', { enabled: true });
  const SER = fs.readFileSync(__dirname + '/ser.js', 'utf8');
  const fresh = async () => { await b.go(URL); await b.ev(SER + ';' + HELP); };
  const until = async (expr, ms = 8000) => { const t = Date.now(); while (Date.now() - t < ms) { if (await b.ev(expr)) return; await b.sleep(100); } throw new Error('timeout ' + expr); };
  const run = async js => { await b.ev(js + ';1'); await b.sleep(250); };
  const snap = async (id, title, note, group) => {
    meta.push({ id, title, note, group });
    if (only && !only.includes(id)) return;
    await b.sleep(150);
    const t = await b.ev(`(()=>{const to=document.querySelector('#toast');return window.__ser(document.querySelector('#win'),to.classList.contains('on')?[to]:[])})()`);
    t.name = id + ' · ' + title;
    fs.writeFileSync(`${__dirname}/states/${id}.json`, JSON.stringify(t));
    await b.shot(`${__dirname}/states/${id}.png`);
    console.log(id, JSON.stringify(t).length);
  };
  const boot = async () => { await fresh(); await run(`$c('[data-do=picktender][data-i="0"]')`); await run(`$c('[data-do=pickfolder][data-f="Default"]')`); await until(`ui.view==='list'&&!!ui.scan`); await b.sleep(300); };
  const finish = async () => { await run(`$c('.demoscan')`); await b.ev(`document.querySelector('#toast').classList.remove('on');1`); };
  const CORR = 'Our Chain of Responsibility controls follow the NHVR Safety Management System: telematics fatigue and speed monitoring, load-restraint checks before every dispatch, and quarterly CoR audits reported to the board.';

  /* ---------- happy flow ---------- */
  await fresh();
  await snap('H01', 'Choose a tender', 'Ray opens on an unlinked document and asks which Tenderfy tender it belongs to. Nothing else in the pane works until a tender is picked.', 'happy');
  await run(`$c('[data-do=picktender][data-i="0"]')`);
  await snap('H02', 'Choose a folder', 'Pick the tender folder the document is filed under, or create a new one. Back returns to the tender list.', 'happy');
  await b.ev(`$c('[data-do=pickfolder][data-f="Default"]');1`); await b.sleep(700);
  await snap('H03', 'Reading the document', 'Ray reads the file section by section in place. Nothing is copied out of Word; the user can keep working.', 'happy');
  await until(`ui.view==='list'&&!!ui.scan`); await b.sleep(250); await run(`$top()`);
  await snap('H04', 'Ray scanning the Response Library', 'Every open question shows "Ray is analysing". The scan card sits above Apply to document. Rows stay clickable, so answering can start right away.', 'happy');
  await run(`$c('.demoscan')`); await run(`$top()`);
  await snap('H05', 'Analysis finished · autofilled', 'Toast reports analysed / autofilled / still open. Library matches are already in the document as tracked changes and tagged "Ray autofilled". The Apply button counts questions in the document.', 'happy');
  await run(`$see('.wr[data-q="3.7"]')`);
  await snap('H06', 'Open questions in the list', 'Questions Ray found no answer for stay Open with an inline "Click to answer" field. Short answers can be written and inserted right here.', 'happy');
  await run(`$c('.wr[data-q="3.7"]')`);
  await snap('H07', 'Question card · empty', 'Clicking a row opens the detail card: section, full question, editor, Ray box. Insert & next stays disabled until there is an answer.', 'happy');
  await run(`$type('#edbody','If a specified product becomes unavailable we notify council in writing within two business days, propose an equivalent AS/NZS 4130 certified product with test certificates, and only substitute once council approves in writing. Price is held at the tendered rate.')`);
  await snap('H08', 'Answer written', 'Typing in the editor enables Insert & next. Previous / Next Question move through the queue without inserting.', 'happy');
  await run(`$c('#primbtn')`); await b.sleep(250);
  await snap('H09', 'Insert & next', 'The answer lands in the document as a tracked change and the card slides to the next question in the queue.', 'happy');
  await run(`$c('[data-do=list]')`); await run(`$see('.wr[data-q="3.7"]')`);
  await snap('H10', 'Back in the list · Inserted', 'The row now shows the answer with an Inserted pill; the Apply count goes up by one.', 'happy');
  await run(`$c('.wr[data-q="3.2"] .t b')`);
  await snap('H11', 'Autofilled answer · review', 'An autofilled question opens with its library answer in the editor and a "Ray autofilled" tag. Update in document stays disabled until something changes.', 'happy');
  await run(`$type('#edbody','We hold buffer stock of the full HDPE range at our Bundaberg depot (opened 2025), with weekly replenishment from Brisbane. Standard orders are delivered within 2 business days; urgent orders confirmed by 10am are delivered the same day.')`);
  await snap('H12', 'Edit → Update in document', 'Editing an inserted answer enables Update in document, which rewrites it as a tracked change.', 'happy');
  await run(`$c('[data-do=update]')`); await run(`$c('[data-do=list]')`);
  await run(`$see('.wr[data-q="5.5"]')`); await run(`$type('.wr[data-q="5.5"] .qa .in','Telematics fatigue and speed monitoring, pre-dispatch load-restraint checks.')`); await run(`document.activeElement.blur()`);
  await run(`$see('.wr[data-q="6.4"]')`); await run(`$type('.wr[data-q="6.4"] .qa .in','No departures from the Conditions of Contract.')`); await run(`document.activeElement.blur()`);
  await run(`$see('.wr[data-q="5.5"]')`);
  await snap('H13', 'Drafts ready to apply', 'Answers left mid-typing are kept as drafts with a "Click to insert" pill. Apply to document inserts every ready draft at once.', 'happy');
  await run(`$c('.cta [data-do=insall]')`);
  await snap('H14', 'Apply to document', 'All ready drafts land as tracked changes in one go; the count updates. Accept or reject them from Word\'s Review tab.', 'happy');

  /* ---------- edge cases ---------- */
  await boot();
  await run(`$see('.wr[data-q="8.3"]')`); await run(`$type('.wr[data-q="8.3"] .qa .in','No conflicts of interest to declare.')`);
  await snap('E01', 'Answering while Ray is still analysing', 'The inline field works during the scan. A quick answer can be inserted before Ray finishes; Ray skips anything already answered.', 'edge');
  await run(`$c('.wr[data-q="2.3"]')`);
  await snap('E02', 'Opening a question Ray is still analysing', 'The card shows Ray searching the Response Library for this question. The user can wait or go back to the list.', 'edge');
  await finish(); await run(`$c('[data-do=list]')`);
  await run(`$see('.wr[data-q="5.5"]')`);
  await snap('E03', 'No library match', 'Questions with no Response Library match stay Open with "Click to answer". Nothing is invented.', 'edge');
  await run(`$type('.wr[data-q="5.5"] .qa .in','Audited annually by an NHVR-accredited assessor.')`);
  await snap('E04', 'Quick inline answer', 'A short answer typed into the row. The arrow inserts it straight into the document; the expand icon opens the full editor.', 'edge');
  await run(`$type('.wr[data-q="5.5"] .qa .in','Our CoR controls follow the NHVR Safety Management System: telematics fatigue and speed monitoring, load-restraint checks, quarterly audits.')`);
  await snap('E05', 'Inline answer getting long', 'Past ~85 characters a note suggests the full editor (formatting, tables, Ray). Clicking it carries the typed text across.', 'edge');
  await run(`document.activeElement.blur()`);
  await snap('E06', 'Left mid-typing → draft kept', 'Clicking away keeps the text as a draft (Ready) with "Click to insert" instead of losing it.', 'edge');
  await run(`$see('.wr[data-q="5.4"]')`);
  await snap('E07', 'Assigned to someone else', 'Rows assigned to a teammate show their avatar, name and due day. You can still click to answer.', 'edge');
  await run(`$top()`); await run(`$see('.wr[data-q="3.1"]')`);
  await snap('E08', 'Edited by a teammate in Word', 'If Mia changes an answer directly in the document, the row flags it so nobody overwrites her edit.', 'edge');
  await run(`$c('.wr[data-q="3.1"] .t b')`);
  await snap('E09', 'Teammate edit · card', 'The card explains Mia changed it after Ray drafted it and shows her version in the editor.', 'edge');
  await run(`$c('[data-do=list]')`); await run(`$see('.wr[data-q="3.2"] .more')`); await run(`$c('.wr[data-q="3.2"] .more')`);
  await snap('E10', 'Long answer · Show more', 'Answers clamp to two lines; Show more expands in place, Show less collapses.', 'edge');
  await run(`$c('.wr[data-q="7.4"]')`);
  await snap('E11', 'Card for an open question', 'Empty editor, disabled Insert & next. Previous / Next Question and Not a Question stay available.', 'edge');
  await run(`$c('.hasg')`);
  await snap('E12', 'Assign from the card header', 'Assign User in the header opens the people menu to assign or reassign the question inline.', 'edge');
  await run(`document.querySelector('.cmenu')?.remove()`);
  await run(`$c('.rffile')`);
  await snap('E13', 'Generate from a file', 'The paperclip opens an in-pane picker: type a Tenderfy file name or upload one, then Generate.', 'edge');
  await run(`$c('.gdlg [data-do=genfile]')`);
  await run(`Q['7.4'].txt='Professional indemnity is not applicable: the contract is supply only with no design or advice component. If council requires it, we can provide $5M cover through our broker within 10 business days.';$c('[data-do=refine]')`);
  await b.sleep(50);
  await snap('E14', 'Ray generating a draft', 'Generate with an empty editor drafts from the Response Library. Usually a few seconds; the user can keep working in Word.', 'edge');
  await until(`!ui.drafting['7.4']`); await b.sleep(200);
  await snap('E15', 'Draft ready in the card', 'Ray\'s draft lands in the editor for reading first. Refine with Ray, undo/redo Ray\'s change, then Insert & next.', 'edge');
  await run(`$c('[data-do=fullscreen]')`);
  await snap('E16', 'Full-screen editor (Office dialog)', 'Open in full opens an Office dialog with the question, owner and status on the left and a page-framed editor. Insert sends the text back to the pane, which writes it.', 'edge');
  await run(`$c('[data-do=dlgclose]')`); await run(`$c('.qnaq')`); await run(`$c('[data-do=list]')`);
  await run(`$c('[data-do=sec][data-s="X"]')`); await run(`$see('[data-do=sec][data-s="X"]')`);
  await snap('E17', 'Not a Question', 'Dismissed items leave the queue and the count, and collect in a Not a Question section with Restore.', 'edge');
  await run(`$top()`); await run(`$c('[data-do=filter][data-f=mine]')`);
  await snap('E18', 'Assigned to me', 'The Assigned switch narrows the list to questions assigned to you.', 'edge');
  await run(`$c('[data-do=filter][data-f=all]')`); await run(`$sel('whosel','MW')`);
  await snap('E19', 'Filter by person', 'In All, the person filter shows one teammate\'s questions across sections.', 'edge');
  await run(`$sel('whosel','')`); await run(`$sel('stfsel','ready')`);
  await snap('E20', 'Status filter with no results', 'Status filters (Inserted / Ready / Open) keep the sections and say when one has nothing in that state.', 'edge');
  await run(`$sel('stfsel','')`); await run(`$c('.bell')`);
  await snap('E21', 'Notifications', 'The bell lists assignments and teammate answers; clicking one opens that question.', 'edge');
  await run(`document.querySelector('.cmenu')?.remove()`); await run(`$c('.wr[data-q="1.1"]')`);
  await snap('E22', 'First in the queue', 'Previous Question is disabled on the first item; Next Question is disabled on the last. Fields in the Tenderer Details Form use the same card.', 'edge');

  fs.writeFileSync(__dirname + '/states/meta.json', JSON.stringify(meta, null, 1));
  b.close();
})().catch(e => { console.error(e); process.exit(1); });
